name: CI

on:
  pull_request:
  push:
      branches:
      - master

jobs:
  run-tests:
    runs-on: [ubuntu-latest]

    env:
        DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DEV_DSN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Set up python3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Run tests
      run: |
        pip install pytest-cov django
        pytest --cov=./ --cov-report=xml

    - name: Report test coverage to DeepSource
      run: |
        curl https://deepsource.io/cli | sh
        # Send the report to DeepSource
        git config --global --add safe.directory $PWD
        ./bin/deepsource report --analyzer test-coverage --key python --value-file ./coverage.xml
        ./bin/deepsource report --analyzer test-coverage --key kotlin --value-file ./coverage.xml
        ./bin/deepsource report --analyzer test-coverage --key swift --value-file ./coverage.xml
        ./bin/deepsource report --analyzer test-coverage --key dart --value-file ./coverage.xml
